# Generated by Django 4.0.3 on 2022-04-06 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='имя')),
                ('lastname', models.CharField(max_length=20, verbose_name='фамилие')),
                ('user_name', models.CharField(max_length=30, verbose_name='имя пользователя в телеграмме')),
                ('live', models.IntegerField(verbose_name='жизнь пользователя')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='пост')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='время добаления')),
                ('type_challenge', models.CharField(max_length=50, verbose_name='тип задания')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserAndPost.members')),
            ],
        ),
    ]
