# Generated by Django 4.0.3 on 2022-04-06 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAndPost', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Состояние'),
        ),
    ]
